### ISSUE TITLE
JSON-RPC batch requests not supported

### ISSUE THREAD

**Issue by nikitinsm** [alorence/django-modern-rpc#11]
Sending batch requests causes "Invalid request, Payload object must be a struct" error.

Batch requests feature is part of 2.0 spec, please remove "JSON-RPC 2.0 support" notice in your documentation or implement this feature.

**Comment by alorence** [comment]
Hi,

Indeed, batch requests are currently not supported. Since this feature cannot be simply added with the current state of the code, I started to work on a huge refactoring of the core module, in order to support batch requests and some new features.

**Comment by alorence** [comment]
Hi Sergey,

I just pushed the new release of the library. As explained before, this release introduce support for JSON-RPC batch requests as well as other improvements. See changelog for more information. The release has tag 0.9.0 and is already available on Pypi: https://pypi.python.org/pypi/django-modern-rpc/0.9.0

Best regards

**Comment by nikitinsm** [comment]
Thanks a lot!
