### ISSUE TITLE
Support params as dict (with keywords)

### ISSUE THREAD

**Issue by svendev** [alorence/django-modern-rpc#12]
Currently, the parser (JSON in this case) only allows for list-style params. As the RFC allows for params to be provided by-position (as an array) or by-names (as an object/dict), the following change in views.py would accomplish this:

```
--- test/python3.4/site-packages/modernrpc/views.py	2017-09-29 17:29:49.783385708 -0400
+++ lib/python3.4/site-packages/modernrpc/views.py	2017-09-29 17:25:58.539645454 -0400
@@ -113,5 +113,8 @@
 
                     # Call the python function associated with the RPC method name
-                    result = rpc_method.execute(*params, **kwargs)
+                    if isinstance(params, list):
+                        result = rpc_method.execute(*params, **kwargs)
+                    else:
+                        result = rpc_method.execute(params, **kwargs)
```
The parser itself probably does not need to be changed since the default empty params as [] (list) wouldn't affect the method being called.

**Comment by alorence** [comment]
Hi,

Thank you very much for the feedback. The JSON-RPC named parameters are not supported in the current release (0.8.0), but the feature has been recently added (see 7c81063). It will be part of the next release, probably next week or the week after that.

Best regards,
Antoine
