### ISSUE TITLE
Problems with kwargs in method called

### ISSUE THREAD

**Issue by nikitinsm** [alorence/django-modern-rpc#18]
I faced conflict with request, entry_point, protocol, handler params name because they are kewords in modernrpc.core 

```
REQUEST_KEY = 'request'
ENTRY_POINT_KEY = 'entry_point'
PROTOCOL_KEY = 'protocol'
HANDLER_KEY = 'handler'
```
would be handy if there will be some workaround to rename keywords per method or settings level

**Comment by alorence** [comment]
Hi Sergey,

Thank you for your feedback. Commit 9341bd2be64e should fix this issue. It will be part of the next release. Feel free to install the lib from current master branch to test.

Cheers

**Comment by alorence** [comment]
Hi Sergey,

The new release 0.11.0 has been published: https://pypi.org/project/django-modern-rpc/

I apology for the time I took to release this, I tried for a few months to fix a strange behavior in tests with Django 2.0. It was finally fixed today, so here it is. The new version, including settings variable to customise `kwargs` dict keys, is now online.
