### ISSUE TITLE
ImportError: cannot import django.utils.inspect in Python 2.7, Django 1.8

### ISSUE THREAD

**Issue by melvinkcx** [alorence/django-modern-rpc#21]
ImportError: cannot import django.utils.inspect in Python 2.7, Django 1.8.

The console shows an ImportError when trying to runserver.

**Comment by alorence** [comment]
[django.utils.inspect is a python module part of Django 1.8](https://github.com/django/django/blob/stable/1.8.x/django/utils/inspect.py). If it can't be imported in your environment, maybe Django is corrupted ?

[Python 2.7 / Django 1.8 combination is fully tested on Travis CI](https://travis-ci.org/alorence/django-modern-rpc/jobs/421946434). This errror has never been reported.

Can you double check your environment is correctly setup ? If you still have this error, can you try to provide more information ?

**Comment by melvinkcx** [comment]
I tried to upgrade to 1.8.19, and it works.
