### ISSUE TITLE
Serializing datetime.date in Python 2

### ISSUE THREAD

**Issue by melvinkcx** [alorence/django-modern-rpc#23]
Is there anyway to make datetime.date object serializable in Python 2 using XML? It keeps throwing a
```
 <Fault -32603: "Internal error: Unable to serialize result as valid XML: cannot marshal <type 'datetime.date'> objects">
```

Thanks.

**Comment by alorence** [comment]
Returning a `datetime.date` is fully supported in Python 2. See [this RPC stub](https://github.com/alorence/django-modern-rpc/blob/master/modernrpc/tests/testsite/rpc_methods_stub/specific_types.py#L47) which is called by this [unit test](https://github.com/alorence/django-modern-rpc/blob/master/modernrpc/tests/test_types.py#L156) [with success](https://travis-ci.org/alorence/django-modern-rpc/jobs/421946434).
Please provide more information

**Comment by alorence** [comment]
I still need to have a more information to help you debug this error. On my side, I can send and receive `datetime.date` objects using XML-RPC protocol without any error. If you can't provide a few line of codes or an example of the issue that I can reproduce, I will close this issue.
