### ISSUE TITLE
Drop Python 3.3 support

### ISSUE THREAD

**Issue by alorence** [alorence/django-modern-rpc#27]
[Python 3.3.0](https://www.python.org/download/releases/3.3.0/) was released on September 29th, 2012 and has now reached its end-of-life. More and more python libraries and packages drop its support. Django requires Python 3.4 [since version 1.9](https://docs.djangoproject.com/en/2.1/releases/1.9/), setuptools from [version 40.0.0](https://github.com/pypa/setuptools/pull/1342).

It became difficult to maintain support for Python 3.3, so django-modern-rpc will require 3.4.

**Comment by hugovk** [comment]
Python 3.4 itself is EOL on 2019-03-16.

https://en.wikipedia.org/wiki/CPython#Version_history

And Django 2.1 and 2.2 support Python 3.5+.

https://docs.djangoproject.com/en/2.1/faq/install/

**Comment by alorence** [comment]
You are right. But django-modern-rpc is still installed by users in a Python 3.4 environment (according to https://pypistats.org/packages/django-modern-rpc). This is not the case for 3.3:

![opera_2019-01-30_20-44-38](https://user-images.githubusercontent.com/1702273/52008035-0a881a00-24d0-11e9-8fdc-dc77ea38d3da.png)

And since supporting 3.4 currently doesn't require additional attention, I don't see any valid reason to drop its support for now. This will probably change in the future, if at some point other dependencies drop 3.4 support.
