### ISSUE TITLE
Documentation omission

### ISSUE THREAD

**Issue by J-A-M** [alorence/django-modern-rpc#3]
On the site
http://django-modern-rpc.readthedocs.io/en/latest/advanced/authentication.html
it does not explicitly state that the @http_basic_auth_login_required decorator needs to be imported from
from modernrpc.auth.basic

Though this error is hidden by the import semantics in apps.py.

**Comment by J-A-M** [comment]
What I meant is that yes, I am aware it has to be explicitly imported, but the prior examples import other decorators from modernrpc.auth.
The http_basic_auth_login_required should be imported from modernrpc.auth.basic - it is this that is missing from the example in the docs.

**Comment by alorence** [comment]
Your right, I will fix the documentation in the next days to mention these imports

**Comment by alorence** [comment]
Oops, issue was fixed from commit 731bea0c23ccd13c
