### ISSUE TITLE
django-modern-rpc not compatible with Django 3.1 (alpha)

### ISSUE THREAD

**Issue by washeck** [alorence/django-modern-rpc#32]
[core.py](https://github.com/alorence/django-modern-rpc/blob/4e292c283cc9e5804b7f7e3d698e2733bd91f04c/modernrpc/core.py#L6) imports `trim_docstring` which has been removed from Django in https://github.com/django/django/commit/f47ba7e78033f39742c3bf491e9b15365cefd0db#diff-618578d61e31fcaf38482c8853e9c5f5

**Comment by alorence** [comment]
Hello,

Thank you for your feedback. I created a new branch to fix issues with Django 3.1 : https://github.com/alorence/django-modern-rpc/tree/django-3.1

The unit tests are currently running. Then I will verify manually the behavior remains unchanged after this update. In the meantime, feel free to test it by installing the lib directly from this branch.

I will update here when a new minor version will be released with this bugfix.

**Comment by alorence** [comment]
Fix were validated by existing tests, and a new one was added to ensure no regression was introduced.
A new minor relelease 0.12.1 has been published (see https://pypi.org/project/django-modern-rpc/), you can update in your project and use the lib with Django 3.1a1.

Regards

**Comment by washeck** [comment]
@alorence Thanks for such a quick update.
