### ISSUE TITLE
Session auth

### ISSUE THREAD

**Issue by luzik** [alorence/django-modern-rpc#33]
Is there any simple way to use Django builtin session auth ?
I am using it with all url requests, after login so there would be nice to make use of it with rpc without frontend keeping login/password.

My code is using `@login_required, @permission_required`. Does it should work with django-modern-rpc ?

Maybe another possibility is a way making use of PyJWT ?

Where to start ?

**Comment by alorence** [comment]
Hi, and sorry for the late answer.

There is currently no builtin support for Django session inside django-modern-rpc but this could be fairly easy to implement.
Using [`set_authentication_predicate`](https://github.com/alorence/django-modern-rpc/blob/master/modernrpc/auth/__init__.py#L10), you can attach a predicate to your RPC Methods. This predicate can access to incoming request object. As long as Django's SessionMiddleware  is enabled, your request will fall into your predicate with the correct session data.

The most difficult part is: _How to initialize the session so following RPC request won't need to set authentication information?_ You should be able to create an "authentication" method, taking needed arguments (user/password, token, app_key/app_secret, etc.) and store enough information in the session so you can quickly re-check authentication in next requests.

See https://django-modern-rpc.readthedocs.io/en/latest/configuration_guide/authentication.html for documention. It may be incomplete but I'm currently re-writing the whole documentation to improve it and cover undocumented parts.

**Comment by luzik** [comment]
Thank You for explanation, I just used your modernrpc.auth.basic with commented out basic auth part. Working great !
