### ISSUE TITLE
Suppress "django-modern-rpc initialized" on django startup

### ISSUE THREAD

**Issue by washeck** [alorence/django-modern-rpc#63]
`modernrpc.apps` loggs the number of RPC methods registered on app registration. While this can provide some debugging info, it is printed every time you run `manage.py` which is bit annoying and in our case even breaks autocomplete for `manage.py`.

I suggest to change the log level of the message to DEBUG, making it possible for users to enable it, but making it disabled by default.

**Comment by alorence** [comment]
Your suggestion seems ok. I already felt that logs produced by the library should be less verbose.
