### ISSUE TITLE
Acceptable "id" field values violate json-rpc 2.0 specification

### ISSUE THREAD

**Issue by moonburnt** [alorence/django-modern-rpc#72]
**Description:**
It seems like the current implementation of "id" field violates json-rpc 2.0 [specification](https://www.jsonrpc.org/specification).

**Expected behavior:**
An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification.

**Actual behavior:**
- Int, string: work as intended
![image](https://github.com/user-attachments/assets/16be8abb-b01f-4382-988b-18092a6859d2)
![image](https://github.com/user-attachments/assets/f9e68ba0-8ddf-40c3-a41a-06c03811121b)

- A negative integer: work (it does not seem to be against the spec, but violates your own error message, see 'null value' below)
![image](https://github.com/user-attachments/assets/c979ed7e-f4f6-4e5d-995a-8c88b7599803)

- A number with decimal part: work as intended (its discouraged but supported)
![image](https://github.com/user-attachments/assets/f761bcb3-4e08-42fd-862b-e85106f74d14)

- An empty list: work (should not, I assume?)
![image](https://github.com/user-attachments/assets/54fccac3-cdba-44ee-b785-68231214002d)

- A list with data: work (should not)
![image](https://github.com/user-attachments/assets/481603d0-e149-4cbe-8c77-508c078f122d)

- An empty dict: work (should not, I assume?)
![image](https://github.com/user-attachments/assets/f9b442a9-ad5f-46e1-a096-73964a70548b)

- A dict with data: work (should not)
![image](https://github.com/user-attachments/assets/702e68c8-8217-4bd6-9922-5e4077bfc0a4)

- A null value: does not work ([it should, while its discouraged](https://www.jsonrpc.org/specification#id1). Also the error message incorrectly specifies that 'id' must be a positive integer, which is wrong as we've seen above)
![image](https://github.com/user-attachments/assets/acf10d27-8c81-4f64-b7d0-6b85683a783c)

**Comment by alorence** [comment]
Hi @moonburnt and many thanks for this complete issue.

I am currently away from keyboard for a few days, but will check this one as soon as possible. 

I totally agree, the library should do its best to respect the standard. Currently, handling of 'id' field is invalid. I am pretty sure this can be easily fixed, in addition, it should be very easy to test too. I will work on it.

Best regards
