### ISSUE TITLE
API versioning with different entrypoint not possible as method names are globally registered

### ISSUE THREAD

**Issue by hwalinga** [alorence/django-modern-rpc#74]
I try to make a versioned API. But a change in a method by setting it to different entrypoints is not possible because the method names are globally registered. 

The docs seem to suggest this is possible. 

```
urlpatterns = [
    path("rpc", RPCEntryPoint.as_view(enable_doc=True, entry_point='apiV1')),
    path('rpcV2/', RPCEntryPoint.as_view(entry_point='apiV2')),
]
```

```
@rpc_method(name="math.increace", entry_point="apiV1")
def increace_v1(x):
    return x + 1


@rpc_method(name="math.increace", entry_point="apiV2")
def increace_v2(x):
    return x + 2
```

Error:

```
django.core.exceptions.ImproperlyConfigured: A RPC method with name math.increace has already been registered
```

Maybe it is possible to namespace the methods by prefixing their `entry_point`? What do you think is an appropriate solution to this?

**Comment by alorence** [comment]
Hi,

Thank you for your feedback. This should definitely be fixed, as there is no valid reason to prevent 2 procedures to be registered with the same name in 2 different endpoint.

I have some ideas for a big refactoring of the library to provide a V2 with a slighly improved but modified public API. But I don't know how much time it will take to perform this rewrite.

I will try to fix this issue quickly using the registry.
