### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by aplicacionamedida** [alorence/django-modern-rpc#9]
Hi Antoine,
There is an error in docs:
http://django-modern-rpc.readthedocs.io/en/latest/advanced/authentication.html

`set_authentication_predicate` now uses params instead of a variable number of arguments: *args

This should be fixed in docs:
```
    set_authentication_predicate(my_predicate_with_params, params=('param_1', 42))
```

**Comment by alorence** [comment]
Thank you for your report. The documentation has been updated.
